import { useState } from "react"
import axios from "axios"

export default function Summary({ summary, apiUrl }) {
  const [downloading, setDownloading] = useState(false)
  const [downloaded, setDownloaded] = useState(false)
  const [audioError, setAudioError] = useState("")

  const handleDownloadAudio = async () => {
    setDownloading(true)
    setAudioError("")
    try {
      const response = await axios.post(
        `${apiUrl}/tts`,
        { text: summary },
        { responseType: "blob" }
      )
      // Create a download link and click it automatically
      const url = window.URL.createObjectURL(new Blob([response.data]))
      const link = document.createElement("a")
      link.href = url
      link.setAttribute("download", "study-overview.wav")
      document.body.appendChild(link)
      link.click()
      link.remove()
      window.URL.revokeObjectURL(url)
      setDownloaded(true)
      setTimeout(() => setDownloaded(false), 3000)
    } catch (err) {
      setAudioError("Could not generate audio. Make sure Flask is running.")
    } finally {
      setDownloading(false)
    }
  }

  // Format summary — turn bullet points into styled list
  const formatSummary = (text) => {
    const lines = text.split("\n").filter(l => l.trim())
    return lines.map((line, i) => {
      const isBullet = line.trim().startsWith("•") ||
                       line.trim().startsWith("-") ||
                       line.trim().startsWith("*")
      return (
        <div key={i} style={{
          display: "flex",
          gap: "10px",
          alignItems: "flex-start",
          marginBottom: "10px",
          padding: isBullet ? "10px 14px" : "0",
          background: isBullet ? "var(--sage-light)" : "transparent",
          borderRadius: isBullet ? "var(--radius-sm)" : "0",
          borderLeft: isBullet ? "3px solid var(--sage)" : "none",
        }}>
          {isBullet && (
            <span style={{
              color: "var(--sage)",
              fontWeight: "700",
              fontSize: "16px",
              marginTop: "1px",
              flexShrink: 0,
            }}>
              ✦
            </span>
          )}
          <p style={{
            fontSize: "15px",
            lineHeight: "1.7",
            color: "var(--text)",
            fontWeight: isBullet ? "500" : "400",
          }}>
            {line.replace(/^[•\-\*]\s*/, "")}
          </p>
        </div>
      )
    })
  }

  return (
    <div>
      {/* Card */}
      <div style={{
        background: "var(--surface)",
        borderRadius: "var(--radius-lg)",
        border: "1px solid var(--border)",
        boxShadow: "var(--shadow-md)",
        overflow: "hidden",
      }}>
        {/* Card header */}
        <div style={{
          padding: "20px 28px",
          borderBottom: "1px solid var(--border)",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          background: "var(--surface-2)",
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <div style={{
              width: "32px", height: "32px",
              background: "var(--sage)",
              borderRadius: "8px",
              display: "flex", alignItems: "center",
              justifyContent: "center",
              fontSize: "16px",
            }}>
              📝
            </div>
            <div>
              <h2 style={{ fontSize: "17px", color: "var(--text)" }}>
                AI Summary
              </h2>
              <p style={{ fontSize: "12px", color: "var(--text-muted)" }}>
                Generated by local Llama model
              </p>
            </div>
          </div>

          {/* Download Audio Button */}
          <button
            onClick={handleDownloadAudio}
            disabled={downloading}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "7px",
              background: downloaded
                ? "var(--success-bg)"
                : "var(--sage)",
              color: downloaded ? "var(--success)" : "white",
              border: downloaded
                ? "1.5px solid var(--success)"
                : "none",
              borderRadius: "var(--radius-sm)",
              padding: "9px 18px",
              fontSize: "13px",
              fontWeight: "600",
              transition: "all 0.2s",
              boxShadow: downloaded
                ? "none"
                : "0 2px 8px rgba(124,158,135,0.35)",
            }}
            onMouseEnter={e => {
              if (!downloading && !downloaded) {
                e.currentTarget.style.background = "var(--sage-dark)"
                e.currentTarget.style.transform = "translateY(-1px)"
              }
            }}
            onMouseLeave={e => {
              if (!downloading && !downloaded) {
                e.currentTarget.style.background = "var(--sage)"
                e.currentTarget.style.transform = "translateY(0)"
              }
            }}
          >
            {downloading ? (
              <>
                <span style={{
                  width: "14px", height: "14px",
                  border: "2px solid rgba(255,255,255,0.3)",
                  borderTop: "2px solid white",
                  borderRadius: "50%",
                  display: "inline-block",
                  animation: "spin 0.7s linear infinite",
                }} />
                Generating...
              </>
            ) : downloaded ? (
              <> ✓ Downloaded!</>
            ) : (
              <> 🔊 Download Audio Overview</>
            )}
          </button>
        </div>

        {/* Summary content */}
        <div style={{ padding: "28px" }}>
          {formatSummary(summary)}
        </div>
      </div>

      {audioError && (
        <div style={{
          marginTop: "12px",
          padding: "12px 16px",
          background: "var(--error-bg)",
          border: "1px solid #F5C6C6",
          borderRadius: "var(--radius-sm)",
          fontSize: "13px",
          color: "var(--error)",
        }}>
          ⚠️ {audioError}
        </div>
      )}

      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  )
}